# 插件名称: QQ白名单
# 作者: bilibili_Xiao_M aka LazyCat aka MrXiaoM
# Github: https://www.github.com/MrXiaoM/MiraiBukkit
# 使用库 Mirai 1.3.3

name: QQWhiteList
main: top.mrxiaom.qqwhitelist.Plugin
version: beta1.0
author: DoomsdaySociety
commands:
  qqwhitelist:
    description: awa